### ISSUE TITLE
Implement `gwdt_computecosts` MEX

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/topotoolbox3#21]

**Comment by wkearn** [comment]
@wschwanghart: I noticed that #11 fixed the values of `CarveMinVal = 0.1` and `tweight=1` here (this is the section that libtopotoolbox's `gwdt_computecosts` replaces):

https://github.com/TopoToolbox/topotoolbox3/blob/3bcaa3efc9177f3d052546af9b8e6340c491c7b4/toolbox/%40FLOWobj/private/createAuxiliaryTopo.m#L132-L160

Those constants are currently hard-coded in libtopotoolbox to `CarveMinVal = 0.1` and `tweight = 2`, which were the defaults before #11. Should those be fixed to the new values or do we want them to be able to be changed by the user? libtopotoolbox could also not apply the transformation and return the equivalent of `maxdepth - D(CC.PixelIdxList{r})`, which could then be transformed as needed.

**Comment by wschwanghart** [comment]
I think that I've never changed those options. `tweight` may be required to enforce a steeper and more pronounced auxiliary elevations, but again, in practice this was never really relevant. Thus, I think both values could be fixed.
